version: "3"

services:
  db:
    image: mongo
    command: mongod
    volumes:
      - ./data/db:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017
  admin:
    image: gunicorn-server
    volumes:
      - ./tci-admin:/app
      - ~/.ssh:/root/.ssh:ro
    links:
      - db
    ports:
      - 5001:80
  researchers:
    image: gunicorn-server
    volumes:
      - ./tci-researchers:/app
      - ~/.ssh:/root/.ssh:ro
    links:
      - db
    ports:
      - 5002:80
