version: "3"

services:
  db:
    image: mongo
    command: mongod --auth
    volumes:
      - ./data/db:/data/db
    expose:
      - 12017
    ports:
      - 12017:27017

  db-api:
    image: mongo
    command: mongod --auth
    volumes:
      - ./data/db-api:/data/db
    expose:
      - 12018
    ports:
      - 12018:27017

  admin:
    image: gunicorn-server
    volumes:
      - ./tci-admin:/app
      - ~/.ssh:/root/.ssh:ro
      - ./settings.json:/settings.json
    links:
      - db
    ports:
      - 5001:80

  researchers:
    image: gunicorn-server
    volumes:
      - ./tci-researchers:/app
      - ~/.ssh:/root/.ssh:ro
      - ./settings.json:/settings.json
      - ./uploads:/app/uploads
    links:
      - db
    ports:
      - 5002:80

  online:
    image: gunicorn-server
    volumes:
      - ./tci-online:/app
      - ~/.ssh:/root/.ssh:ro
      - ./settings.json:/settings.json
    links:
      - db
    ports:
      - 5003:80

  professionals:
    image: gunicorn-server
    volumes:
      - ./tci-professionals:/app
      - ~/.ssh:/root/.ssh:ro
      - ./settings.json:/settings.json
    links:
      - db
    ports:
      - 5004:80

  api:
    image: gunicorn-server
    volumes:
      - ./tci-api:/app
      - ~/.ssh:/root/.ssh:ro
      - ./settings.json:/settings.json
    links:
      - db-api
    ports:
      - 5005:80
